apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site
global:
  docker_registry: registry.cicd.stg.taco
  admin_keyring: abcdefghijk
  repository: http://helm-chart-repository
charts:
  - name: glance
    source:
      repository: $(repository)
      version: 1.0.0
    override:
      conf.ceph.admin_keyring: $(admin_keyring)
