apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site
global:
  docker_registry: registry.cicd.stg.taco
  admin_keyring: abcdefghijk
  repository: http://helm-chart-repository
  storageClassName: ceph
charts:
  - name: glance
    source:
      repository: $(repository)
      version: 1.0.0
    override:
      volumeClaimTemplates: 
      - metadata:
          name: elasticsearch-data
        spec:
          storageClassName: $(storageClassName)
