name: RunKustomize 

on:
  pull_request:
    branches: [ master ]

jobs:

  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Kustomize binary
      run: |
        cat README.md | grep -m 1 "* kustomize" | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' > .kustomize_version
        GO111MODULE on go get sigs.k8s.io/kustomize/kustomize/v3@v$(cat $HOME/.kustomize_version)

    - name: Build
      run: |
        echo ">>> go build HelmValuesTransformer.go <<<"
        mkdir -p ~/.config/kustomize/plugin/openinfradev.github.com/v1/helmValuesTransformer
        cd plugin/openinfradev.github.com/v1/helmvaluestransformer
        go build -buildmode plugin -o HelmValuesTransformer.so ~/.config/kustomize/plugin/openinfradev.github.com/v1/helmValuesTransformer/HelmValuesTransformer.so/HelmValuesTransformer.go
        echo ">>> build completed! <<<"
        ls -h

    - name: Run Plugin
      run: kustomize build --enable_alpha_plugins examples/helmvalues
